name: Update PR on author input

on:
  - issue_comment
  - pull_request_review_comment

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
        # https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review_comment
        if: github.event.comment.user.id == github.event.issue.user.id || github.event.comment.user.id == github.event.pull_request.user.id
        with:
          labels: hint/needs-author-input