name: Testground Publish
on:
  release:
    types: [created]

# on:
#   push:
#     branches:
#       - 'main'
# on:
#   release:
#     types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lsenta/testground:${{ github.event.release.tag_name }}
          file: ./Dockerfile.testground
          platforms: linux/arm64,linux/amd64
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lsenta/testground:sidecar-${{ github.event.release.tag_name }}
          file: ./Dockerfile.sidecar
          platforms: linux/arm64,linux/amd64
  releases-binary:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.29
        with:
          release_tag: latest # remove me when we move this to "release: [created]".
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "testground"
          ldflags: "-s -w -X github.com/testground/testground/pkg/version.GitCommit=${TG_VERSION}"
          extra_files: LICENSE-APACHE LICENSE-MIT README.md
